### ISSUE TITLE
[Bug] perplexity ：[code: 400 | message: Cannot set both presence_penalty and frequency_penalty.]

### ISSUE THREAD

**Issue by ConnorCHN** [lobehub/lobe-chat#1368]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Edge

### 🐛 问题描述

![微信截图_20240223181100](https://github.com/lobehub/lobe-chat/assets/8830361/8fcc5105-f86a-4dc3-b8e8-de27ac705007)
![微信截图_20240223181119](https://github.com/lobehub/lobe-chat/assets/8830361/226256b9-cc1a-42bd-b351-f59ffcee9b7c)
![微信截图_20240223181436](https://github.com/lobehub/lobe-chat/assets/8830361/0c50cf5a-b1d8-42b2-82a3-12988ddb6b10)

issue report with Chinese ：
如图所示，Vercel部署的，Perplexity的Key检查通过了的，但是对话报错 "code : 400", 报错内容提示frequency_penalty和presence_penalty不能同时设置。我把frequency_penalty 和 presence_penalty 同时设置为0.0 之后就不再报错了。

issue report with English：
As shown in the picture, Vercel deployed, Perplexity's Key check passes, but the dialog reports "code : 400", which indicates that frequency_penalty and presence_penalty cannot be set at the same time. I set both frequency_penalty and presence_penalty to 0.0 and the error stopped.

**Comment by arvinxx** [comment]
@gijigae please help to check this issue~

**Comment by gijigae** [comment]
@arvinxx, again need your help. The issue is Perplexity requires either frequency_penalty or presence_penalty, not both. However, the DEFAULT_AGENT_CONFIG returns both values. What would be the best approach to conditionally pass only one value for the Perplexity models?

https://github.com/lobehub/lobe-chat/blob/ec76917a28981370ff673a8e53893e28f06f47ef/src/const/settings.ts#L30C1-L46C3
