### ISSUE TITLE
[Bug] ollama models need to be "refreshed" when first time use

### ISSUE THREAD

**Issue by cnkang** [lobehub/lobe-chat#2101]
### 💻 Operating System

macOS

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

docker-compose中有如下设置：
OLLAMA_PROXY_URL=http://172.17.0.1:11434/v1
OLLAMA_MODEL_LIST=-all,+qwen:32b,+llama3:8b
首次登录后:
![image](https://github.com/lobehub/lobe-chat/assets/555836/11fa5cbd-54ad-4ec7-8370-d9a3854b1fa9)
进入设置显示如下：
![image](https://github.com/lobehub/lobe-chat/assets/555836/9a60d0a7-975a-4d3a-a062-82b3152d13ca)
点击“重置”刷新后可以正常获取模型：
![image](https://github.com/lobehub/lobe-chat/assets/555836/a74b670a-c2ca-4686-b3c1-a6736aa296d9)
后续可以继续正常使用：
![image](https://github.com/lobehub/lobe-chat/assets/555836/f70c9890-d390-45da-a682-e7268f156fc2)

### 🚦 Expected Behavior

希望设定好的自定义的ollama模型首次进入后不需要去再设置那里刷新一下才能用。

### 📷 Recurrence Steps

用无痕浏览进入即可复现

**Comment by fgprodigal** [comment]
v0.155.1 问题依然存在

**Comment by xiaolinfrank** [comment]
接力楼上，v0.156.2 问题依然存在

**Comment by CoreJa** [comment]
Problem still exists in v0.162.17. @arvinxx 

It is configured with no other LLM providers at all, just ollama itself.

Running docker cmd:

> docker run -d --rm -p 3210:3210 -e OLLAMA_PROXY_URL=http://host.docker.internal:11434/v1 -e ENABLED_OPENAI=0 -e OLLAMA_MODEL_LIST='-all,+wangshenzhi/llama3-8b-chinese-chat-ollama-q4:latest=ME-llama3<8192>' lobehub/lobe-chat

![image](https://github.com/lobehub/lobe-chat/assets/28624864/1b4478ca-bf7d-465c-b739-a166c55f61eb)

**Comment by bingoct** [comment]
problem still exists  in `docker.io/lobehub/lobe-chat:v0.162.21`

##  environment
```yaml
    environment:
      - FEATURE_FLAGS=-check-updates,-welcome_suggest
      - DEFAULT_AGENT_CONFIG="model=qwen2:7b;provider=ollama"
      - ENABLED_OPENAI=0
      - OLLAMA_PROXY_URL=http://192.168.3.100:11434
      - OLLAMA_MODEL_LIST=+qwen2:7b,+codellama:7b,+phi3:3.8b,-hhao/openbmb-minicpm-llama3-v-2_5:latest,-llama3:latest
```

## Bug Description
1. at first time, i open. then `OLLAMA_PROXY_URL` and  is not right!
  ![image](https://github.com/lobehub/lobe-chat/assets/47520890/cdb0e5a9-ff12-4c03-a9d4-4142a5ed31ba)
  However, lube-chat's default agent can still be used.
  ![image](https://github.com/lobehub/lobe-chat/assets/47520890/0fe25fd8-d701-43d1-a01c-74b3d819a035)
  and in ollama server log, it works indeedly.
    ```plaintext
    [GIN] 2024/06/11 - 13:28:53 | 200 |   14.1375523s |   192.168.3.100 | POST     "/api/chat"
    ```

2.  then i click the reset button, `OLLAMA_MODEL_LIST`  works but still remain old default configuration. And `OLLAMA_PROXY_URL` is still not right.
  btw, i check the ollama server log. In fact,it received the request. So i guess the problem migtht happen in fronts.
    ```plaintext
    [GIN] 2024/06/11 - 13:15:01 | 200 |      6.2335ms |   192.168.3.100 | GET      "/api/tags"
    ```
  ![image](https://github.com/lobehub/lobe-chat/assets/47520890/e06f8fe8-2cd4-49ce-b2e7-fe194cf6717e)


3. whatever i set the `OLLAMA_URL` in front, the connect_health_check still fail. 
    ![image](https://github.com/lobehub/lobe-chat/assets/47520890/48dc833a-f0df-4ec2-a67f-a04a21b8d49d)


## Expected Behavior
OLLAMA relate environment variable works right and health_check work right.

**Comment by zidanereal5** [comment]
![图片](https://github.com/lobehub/lobe-chat/assets/123045775/07c6a3fa-0023-4d94-9ec2-9960a68000f2)
同样的问题，环境变量配置未生效，
![图片](https://github.com/lobehub/lobe-chat/assets/123045775/32815df0-e13e-4619-b5ac-b34a816d6932)
需要在配置页面刷新，才可以显示模型。
版本v1.2.3
启动命令如下：
sudo docker run -d -p 4000:3210 \
  -e ENABLED_OPENAI=0 \
  -e OPENAI_API_KEY=sk-EN1ertLm86bO0aO170B5F114271343E580B85e5eF8EeC729 \
  -e OPENAI_PROXY_URL=http://10.2.147.71:3001/v1 \
  -e OPENAI_MODEL_LIST="-all" \
  -e ENABLED_OLLAMA=1 \
  -e OLLAMA_PROXY_URL=http://10.2.147.71:11434 \
  -e OLLAMA_MODEL_LIST="-all,+qwen2:7b<32000:fc>" \
  --name lobe-chat \
  lobehub/lobe-chat:v1.2.3

**Comment by PIKACHUIM** [comment]
v1.18.1 Problem still exists
I am grateful for this project and its contributors, even though it is a flashy but impractical project.

**Comment by arvinxx** [comment]
I think this one is fixed by https://github.com/lobehub/lobe-chat/pull/4038
