### ISSUE TITLE
[Request] Add a way to close the banner on Top

### ISSUE THREAD

**Issue by icnahom** [lobehub/lobe-chat#3463]
### 🥰 Feature Description

![image](https://github.com/user-attachments/assets/ea930610-0a56-490c-8219-e8bb9e397598)

This banner is taking too much space.

### 🧐 Proposed Solution

Allow users to dismiss it.

**Comment by arvinxx** [comment]
you can self-hosting your own instance to remove it

**Comment by RubuJam** [comment]
> So it's on purpose? Is that how you reward early users, by pushing them into a paid model?

This website is for demonstration purposes only and is not recommended for use in a production environment.

**Comment by arvinxx** [comment]
@icnahom as @RubuJam  said, the `chat-preview.lobehub.com` is a demo site for the self-hosting user. We don't suggest to use it in your daily usage.

The banner is not enabled in your own instance.

Maybe you don't know this demo site have a lots of traffic per months and we have to pay a lot for it. It's better for us that our self-hosting users can use their own instance other than the preview site.

It's a more health path for us to continued contribute to LobeChat like this:

1.  a new user to just visit the preview site and check whether LobeChat does he want.

2. if the user is a geek who know self-hosting a lot, he can use Vercel / Docker / Zeabur to deploy his instance for free. And then we don't need to pay the traffic fee for these users —— they afford by themself, and mostly are free.

3. If the user doesn't know self-hosting , he can try with our cloud version and decide to pay or not. 

In this way, we can guarantee the preview site can run for long-term, or it need to be shut down due to high traffic fee.
