### ISSUE TITLE
[Bug] Too slow to open

### ISSUE THREAD

**Issue by nakaboc** [lobehub/lobe-chat#3517]
### 📦 Environment

Vercel

### 📌 Version

Latest

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

Compared with NextChat https://github.com/ChatGPTNextWeb, LobeChat takes x3-5 times time to open the new chat window. Feels like a year!

**Comment by arvinxx** [comment]
please share your screen record to show the slow video? the load on myside is enough to use.

**Comment by nakaboc** [comment]
Both NextChat and Lobe are deployed on the same Vercel with the same Azure OpenAI endpoint and key ---

NextChat took nearly no time to render the chatbox:
https://github.com/user-attachments/assets/4cc8a863-fb57-4c99-ba0b-f990833f092b

Lobe rendered a long loading screen, and the answer took longer time to render as well
https://github.com/user-attachments/assets/6676a9e1-5d77-48bc-aaad-467fe9e1af78

**Comment by arvinxx** [comment]
@nakaboc  There is some different parts of the slow:

1. **the open page slow** : due to LobeChat have much more features than NextChat like token count / Agent Editor / Plugin and so on, we may not to reduce the page size of LobeChat. So the first time to open LobeChat will always slow than NextChat. We may can improve but not so much. But when you open after first, it will speed up due to there is cache in browser.
2. **the chat response slow** : I notice there is a chat opacity, so you much use the LobeChat in database mode. So there are a more latency duration of db connection. But NextChat only support browser storage with 5MB limited (local storage). Using Lobechat's server database mode compare with NextChat's client storage is unfair. If you want to compare the chat response , better to use LobeChat's client db mode. This mode will only use browser DB (IndexedDB with no limitation)  and without network latency.

**Comment by arvinxx** [comment]
Beside, If your using Clerk as Auth provider, there will be a more long time (~2s) to init clerk auth depending on your network.

If you don't need data sync, the client db mode will be much faster than server db mode. In current stage, the cost of cloud data sync is a little bit slow of page loading.

But it all depends on your demand.
