### ISSUE TITLE
[Bug] Can't upload docs on knowledge

### ISSUE THREAD

**Issue by juniorsereno** [lobehub/lobe-chat#4251]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome, Edge

### 🐛 Bug Description

Stuck in upload... already config minio, logto, pgvector.

Database version, self-hosted

![Captura de tela 2024-10-03 134806](https://github.com/user-attachments/assets/89893498-bce5-45a8-b6a4-a7097d9ce64b)

**Comment by Sun-drenched** [comment]
The information you provided is too little to pinpoint your issue, but I suspect the problem is most likely related to MinIO. You can try following the official documentation (https://lobehub.com/docs/self-hosting/server-database/docker-compose) to redeploy MinIO or review the previous deployment process according to the guidelines to see if there were any mistakes.
