### ISSUE TITLE
[Request] Customizable Shortcut for Deleting Conversations

### ISSUE THREAD

**Issue by abix5** [lobehub/lobe-chat#4517]
### 🥰 Feature Description

Currently, there is a keyboard shortcut (option + command + backspace) that deletes the entire conversation, which can be accidentally triggered when using shortcuts for deleting words or lines. This can lead to unintended loss of important conversation history.

### 🧐 Proposed Solution

Introduce an option to customize or disable the keyboard shortcut for deleting the entire conversation. This would help prevent accidental deletions and allow users to configure shortcuts according to their preferences.

### 📝 Additional Information

⚠️ It's frustrating that such a critical action is tied to a keyboard shortcut that is too easy to trigger accidentally. Whoever designed this combination didn't consider the potential for accidental activation. 

😠 This shortcut should be much more complex or difficult to invoke to prevent unintended data loss and user frustration. Additionally, there is no confirmation popup when this combination is used, and there is absolutely no way to undo this operation!

**Comment by arvinxx** [comment]
I think relative issue is https://github.com/lobehub/lobe-chat/issues/556. Which make deleting converation works when focus on input.

Custom Shortcut is on plan but not a high priority feature currently.

@zhuozhiyongde What's your idea?

**Comment by zhuozhiyongde** [comment]
I am not deleting history under any circumstances now, I rarely use the `opt+cmd+backspace` shortcut combination anymore; I just use `opt+n` to create a new conversation. Because for me, although I actually won't go back to look for most of the history again, there is still a small part of content that might need to be reviewed.

Let alone after switching to the database version, the issue of capacity is no longer a problem.

Although I think it's not very necessary, **adding a feature flag to disable this shortcut is also an option** (I think since most people didn't mention this issue before, adding an option in the settings interface is not very cost-effective).

**Comment by abix5** [comment]
I understand your perspective, and I appreciate your feedback. However, I constantly find myself accidentally hitting the option + command keys, which leads to the deletion of lengthy conversations. It's extremely frustrating that when clicking the delete button with a mouse, a confirmation dialog appears, but there is no such safeguard when using the keyboard shortcut. User experience suggests that there should be a confirmation for such a potentially harmful operation as completely deleting a conversation.

**Comment by arvinxx** [comment]
@abix5 after discussion, we plan to remove this shortcut temporally.

**Comment by Konano** [comment]
> @abix5 after discussion, we plan to remove this shortcut temporally.

Heartbroken. I used this feature quite frequently.

Sometimes, I just want to ask GPT something without keeping too much of the temporary conversation history, so I’ve developed the habit of using this shortcut key to clear the current temporary chat. But now, the shortcut key is gone.
