### ISSUE TITLE
High CPU Usage of Lobechat 

### ISSUE THREAD

**Issue by ChenglongWang** [lobehub/lobe-chat#4917]
I have observed abnormally high CPU utilization in LobeChat across both the Progressive Web App (PWA) and conventional web browser versions. Through investigation, I found that:

- The issue persists regardless of the access method (PWA or web browser)
- The high CPU usage occurs even with a clean chat session without user login
- Chat history is not the root cause, as the problem manifests in completely new sessions

Based on these observations, the excessive CPU usage may be related to the UI rendering implementation.

My Machine is MacBook Pro (M4 pro chip) model.
OS: MacOS 15.1.1 

⬇️ After opening the webpage, CPU usage of `Safari Graphics and Media` increases immediately.
<img width="1086" alt="Screenshot 2024-12-07 at 15 44 10" src="https://github.com/user-attachments/assets/4ca7690b-24a0-4dcc-a9cc-611eaf0e4bf7">

⬇️Just opening a New clean page will cause this issue.
<img width="1352" alt="Screenshot 2024-12-07 at 15 44 39" src="https://github.com/user-attachments/assets/eb0a3ad0-5567-4471-93ea-a1cdbe0f8fa9">

### Discussed in https://github.com/lobehub/lobe-chat/discussions/4784

<div type='discussions-op-text'>

<sup>Originally posted by **ChenglongWang** November 25, 2024</sup>
Hi,

I am currently using the Progressive Web App (PWA) version of Lobechat for my daily usage. However, I've noticed that the CPU usage for the Lobechat client is significantly higher compared to other applications, which also caused high battery usage.

Is there a way to address this issue and reduce the CPU consumption? Any recommendations or tips would be greatly appreciated.
Machine:  MacBook Pro M4

Thank you!

<img width="659" alt="Screenshot 2024-11-25 at 12 29 13" src="https://github.com/user-attachments/assets/726f2e32-05cb-4855-8abe-c7fabbe1e6fe">
</div>

**Comment by AiharaMahiru** [comment]
性能问题水深火热啊

**Comment by arvinxx** [comment]
@ChenglongWang we have found it's the banner causing high CPU Usage. And only Safari cause 100%+ CPU Usage, if you switch to Chrome, it will only use about 50%.

<img width="808" alt="image" src="https://github.com/user-attachments/assets/bac1e691-0431-47ac-8e99-fc41ad48a914">

The solution is self-hosting a lobechat instance by yourself using Vercel or your VPS, the self-hosting version will not have this banner. Or you can use our hosted instance: lobechat.com 

As for this issue, we won't plan to fix due to this site is just a preview instance not for the production usage. If you care for the CPU usage, please follow my advice.
